* Overview

This repository contains replication files for the article:

- Ferrari, D. (2024). Does Informing Partisans About Partisan Bias Reduce Partisan Bias? /Journal of Politics/.


Bibtex citation:

#+begin_src latex
@article{ferrari2024does,
author  = {Diogo Ferrari}, 
title   = {Does informing partisans about partisan bias reduce partisan bias?},
year    = {2024},
journal = {Journal of Politics},
number  = {},
pages   = {},
month   = {},
note    = {}, 
volume  = {}
}
#+end_src

The files include:

1. The scripts used to generate the analyses, tables, and figures
2. Data set(s) used in the analyses (except if privacy policy applies)

* System Requirements
** Hardware

The analyses in the manuscript were produced using:
- Intel® Core™ i7-10610U × 8
- 48 GiB RAM

** Software
  
Original settings used to produce the manuscript analyses:

#+BEGIN_SRC R :exports code :results none
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 23.10

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.11.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.11.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/Los_Angeles
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] lubridate_1.9.3        forcats_1.0.0          stringr_1.5.1          dplyr_1.1.4            purrr_1.0.2           
 [6] readr_2.1.5            tidyr_1.3.0            tibble_3.2.1           tidyverse_2.0.0        scales_1.3.0          
[11] rstatix_0.7.2          ggh4x_0.2.8            jtools_2.2.2           patchwork_1.2.0        cowplot_1.1.3         
[16] broom.mixed_0.2.9.5    broom_1.0.6            magrittr_2.0.3         glue_1.7.0             marginaleffects_0.21.0
[21] modelsummary_2.1.1     kableExtra_1.4.0       labelled_2.13.0        dtplyr_1.3.1           readxl_1.4.3          
[26] writexl_1.5.0          multcomp_1.4-26        TH.data_1.1-2          MASS_7.3-60            survival_3.7-0        
[31] mvtnorm_1.2-5          lme4_1.1-35.5          Matrix_1.6-4           sjlabelled_1.2.0       sjmisc_2.8.10         
[36] cobalt_4.5.5           MatchIt_4.5.5          furrr_0.3.1            future_1.34.0          conflicted_1.2.0      
[41] ggdark_0.2.1           gtsummary_2.0.0        ggplot2_3.4.4          RColorBrewer_1.1-3    

loaded via a namespace (and not attached):
 [1] rlemon_0.2.1        sandwich_3.1-0      rlang_1.1.2         snakecase_0.11.1    compiler_4.3.1     
 [6] systemfonts_1.1.0   vctrs_0.6.5         pkgconfig_2.0.3     crayon_1.5.3        fastmap_1.1.1      
[11] backports_1.5.0     labeling_0.4.3      effectsize_0.8.9    pander_0.6.5        utf8_1.2.4         
[16] rmarkdown_2.21      tzdb_0.4.0          haven_2.5.4         nloptr_2.0.3        ragg_1.3.2         
[21] xfun_0.39           cachem_1.0.8        optmatch_0.10.7     chk_0.9.2           parallel_4.3.1     
[26] R6_2.5.1            tables_0.9.28       stringi_1.8.2       parallelly_1.38.0   car_3.1-2          
[31] boot_1.3-30         lmtest_0.9-40       estimability_1.5.1  cellranger_1.1.0    Rcpp_1.0.13        
[36] knitr_1.42          future.apply_1.11.2 zoo_1.8-12          parameters_0.22.1   timechange_0.3.0   
[41] splines_4.3.1       tidyselect_1.2.0    rstudioapi_0.16.0   abind_1.4-5         codetools_0.2-20   
[46] listenv_0.9.1       lattice_0.22-6      bayestestR_0.14.0   withr_2.5.2         coda_0.19-4.1      
[51] evaluate_0.24.0     xml2_1.3.4          pillar_1.9.0        carData_3.0-5       checkmate_2.3.2    
[56] insight_0.20.2      generics_0.1.3      rprojroot_2.0.4     hms_1.1.3           munsell_0.5.0      
[61] minqa_1.2.5         xtable_1.8-4        globals_0.16.3      emmeans_1.10.3      tools_4.3.1        
[66] data.table_1.15.4   grid_4.3.1          datawizard_0.12.2   colorspace_2.1-0    nlme_3.1-165       
[71] performance_0.12.2  cli_3.6.1           textshaping_0.4.0   fansi_1.0.5         viridisLite_0.4.2  
[76] svglite_2.1.3       gtable_0.3.3        digest_0.6.31       farver_2.1.2        memoise_2.0.1      
[81] htmltools_0.5.5     lifecycle_1.0.4    
> print(version)
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          3.1                         
year           2023                        
month          06                          
day            16                          
svn rev        84548                       
language       R                           
version.string R version 4.3.1 (2023-06-16)
nickname       Beagle Scouts               

Time difference of 36.94 mins

> proc.time()
    user   system  elapsed 
2214.466    1.817 2220.404 


#+END_SRC                   

# +BEGIN_SRC python :exports code :results none
# +END_SRC

** Non-standard software and hardware
   :PROPERTIES:
   :CUSTOM_ID: non-standard-software-and-hardware
   :END:
No non-standard software or hardware was used.


* Data Privacy Statement

All data were anonymized.


* Instructions for replication

1. Donwload the replication files from [[https://dataverse.harvard.edu/dataverse/jop][Dataverse]] or clone the repository by running the following command in your terminal:

   #+BEGIN_SRC shell
git clone https://github.com/DiogoFerrari/ferrari2024does.git
   #+END_SRC


2. [@2] Make sure you have the following folder structure in place (it will be automatically created if you are cloning from GitHub or downloaded a =.zip= file with the replication scripts; but it may need to be created manually by you if you downloaded the script files individually).

#+BEGIN_SRC ascii :exports none
.
├── data
│   └── final                        <- folder with data used in the analysis (limited if private policy applies)
├── man                              <- folder with the manuscript (limited if copyright applies)
│   └── tables-and-figures           <- tables and figures (in .pdf, .png. etc) used in the manuscript and online supplement
├── src                              <- scripts for replication
│   └── model                        <- folder with the scripts that contain the analyses
└── README.org                       <- the file you are reading now
#+END_SRC

3. [@3] Run the scripts in the folder =./src/model/=. There might be either R or Python scripts in that folder, or possibly scripts from both languages.


/For R scripts/ (if any)
- Install the libraries used in the script
- Open your terminal
- From the terminal window, navigate to the folder =./src/model/=
- Run from terminal

#+BEGIN_SRC shell
R CMD BATCH --no-save model.R 
#+END_SRC



/For Python scripts/ (if any)
- Open your terminal and navigate to the folder =./src/=
- From that folder, run the following command to install the required libraries:

   #+BEGIN_SRC shell
pip install -r requirements.txt
#+END_SRC

- Navigate to the folder =./src/model/=
- Run from terminal

#+BEGIN_SRC shell
python model.py
#+END_SRC

The scripts will automatically create all tables and figures used in the paper and online supplement and save it in the =./man/tables-and-figures/= folder.

